import Link from 'next/link';

export default function Home() {
  return (
    <main className="min-h-screen p-24">
      <h1 className="text-4xl font-bold mb-8">Welcome to My Shop</h1>
      <p className="mb-4">Generated by AppCreator.</p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="p-6 border rounded-lg">
          <h2 className="text-xl font-bold mb-2">Features</h2>
          <ul className="list-disc pl-5">
            <li>Authentication</li>
          </ul>
        </div>
        
        <div className="p-6 border rounded-lg">
          <h2 className="text-xl font-bold mb-2">Data Models</h2>
          <ul className="list-disc pl-5">
             <li>User</li><li>Product</li><li>Order</li>
          </ul>
        </div>
      </div>
    </main>
  );
}