import { Injectable } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import * as AdmZip from 'adm-zip';

@Injectable()
export class GeneratorService {
    private uploadsDir = path.join(process.cwd(), 'uploads');

    constructor() {
        if (!fs.existsSync(this.uploadsDir)) {
            fs.mkdirSync(this.uploadsDir, { recursive: true });
        }
    }

    getProjectSourcePath(projectId: string) {
        return path.join(this.uploadsDir, `source-${projectId}`);
    }

    async generateProject(projectId: string, config: any): Promise<string> {
        const sourceDir = this.getProjectSourcePath(projectId);

        // Ensure clean state
        if (fs.existsSync(sourceDir)) {
            fs.rmSync(sourceDir, { recursive: true, force: true });
        }
        fs.mkdirSync(sourceDir, { recursive: true });

        // 1. Core Files
        this.createFile(sourceDir, 'package.json', JSON.stringify({
            name: config.appName || 'my-app',
            version: '0.1.0',
            private: true,
            scripts: {
                dev: "next dev",
                build: "next build",
                start: "next start"
            },
            dependencies: {
                "next": "14.0.0",
                "react": "^18",
                "react-dom": "^18",
                "@prisma/client": "^5.0.0"
            },
            devDependencies: {
                "prisma": "^5.0.0"
            }
        }, null, 2));

        this.createFile(sourceDir, 'README.md', `# ${config.appName}\n\nGenerated by AppCreator.`);

        // 2. Prisma Schema (Data Model)
        if (config.entities && Array.isArray(config.entities) && config.entities.length > 0) {
            const prismaDir = path.join(sourceDir, 'prisma');
            if (!fs.existsSync(prismaDir)) fs.mkdirSync(prismaDir);

            let schema = `generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;

            config.entities.forEach((entity: any) => {
                schema += `model ${entity.name} {\n  id String @id @default(uuid())\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n`;
                if (entity.fields) {
                    entity.fields.forEach((field: any) => {
                        schema += `  ${field.name} ${field.type}${field.optional ? '?' : ''}\n`;
                    });
                }
                schema += `}\n\n`;
            });

            this.createFile(prismaDir, 'schema.prisma', schema);
        }

        // 3. UI Pages
        const appDir = path.join(sourceDir, 'app');
        fs.mkdirSync(appDir, { recursive: true });

        const pageContent = `
import Link from 'next/link';

export default function Home() {
  return (
    <main className="min-h-screen p-24">
      <h1 className="text-4xl font-bold mb-8">Welcome to ${config.appName || 'Your App'}</h1>
      <p className="mb-4">Generated by AppCreator.</p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="p-6 border rounded-lg">
          <h2 className="text-xl font-bold mb-2">Features</h2>
          <ul className="list-disc pl-5">
            ${(config.features || []).map((f: string) => `<li>${f}</li>`).join('')}
          </ul>
        </div>
        
        <div className="p-6 border rounded-lg">
          <h2 className="text-xl font-bold mb-2">Data Models</h2>
          <ul className="list-disc pl-5">
             ${(config.entities || []).map((e: any) => `<li>${e.name}</li>`).join('')}
          </ul>
        </div>
      </div>
    </main>
  );
}
    `;
        this.createFile(appDir, 'page.tsx', pageContent);

        // 4. Zip result
        const zip = new AdmZip();
        zip.addLocalFolder(sourceDir);

        const zipName = `project-${projectId}.zip`;
        const zipPath = path.join(this.uploadsDir, zipName);
        zip.writeZip(zipPath);

        return zipName;
    }

    private createFile(dir: string, fileName: string, content: string) {
        fs.writeFileSync(path.join(dir, fileName), content.trim());
    }
}
